(source gnu)
(source org)
(source melpa)

(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-matchit")
(depends-on "evil-numbers")
(depends-on "evil-visualstar")
(depends-on "ace-jump-mode")
(depends-on "key-chord")
(depends-on "surround")

(depends-on "auto-complete")
(depends-on "ac-nrepl")
(depends-on "company")
(depends-on "helm")
(depends-on "helm-cmd-t")
(depends-on "helm-company")
(depends-on "helm-orgcard")
(depends-on "helm-pydoc")
(depends-on "helm-themes")
(depends-on "imenu-anywhere")
(depends-on "popwin")
(depends-on "smex")

(depends-on "f")
(depends-on "s")
(depends-on "dash")

(depends-on "auctex")
(depends-on "latex-extra")

(depends-on "calfw")
(depends-on "org-plus-contrib")

(depends-on "cider")
(depends-on "jedi")
(depends-on "cl-lib-highlight")
(depends-on "clojure-cheatsheet")
(depends-on "clojure-mode")
(depends-on "el-spice")
(depends-on "elisp-slime-nav")
(depends-on "skewer-mode")
(depends-on "js2-mode")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")

(depends-on "unicode-whitespace")
(depends-on "pretty-symbols")
(depends-on "yasnippet")
(depends-on "column-enforce-mode")
(depends-on "flycheck")
(depends-on "magit")
(depends-on "smartparens")

(depends-on "crontab-mode")

(depends-on "circe")
(depends-on "highlight-tail")
(depends-on "elfeed")
(depends-on "lui")
(depends-on "nyan-mode")
(depends-on "nyan-prompt")
(depends-on "tumblesocks")
(depends-on "typing")
